/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.wentware.test.app;

import com.wentware.test.graph.Graph;

public class App {
    public static void main(String[] args) {
        Graph myGraph = new Graph();
    }
}
